### ISSUE TITLE
Rails ignoring factory

### ISSUE THREAD

**Issue by carlosMedrano27** [thoughtbot/factory_bot_rails#362] opened 2020-02-19 22:40 UTC
After running the rails g model command, a factory is not generated instead a fixture is created

**Comment by entcheva** [comment] 2020-03-20 17:45
Hi @carlosMedrano27 - can you provide a code snippet? What was the exact Rails command that you ran? If you have any [factory_bot specific configuration](https://github.com/thoughtbot/factory_bot_rails#configuration) in your project, can you share it here?

**Comment by composerinteralia** [comment] 2020-04-12 14:15
I manually tested the generator in a new Rails application and was not able to reproduce this behavior. It might be worth checking that you have factory_bot_rails in the development section of your Gemfile.

I am going to close this issue for now. Feel free to reopen if there is additional context that would help us reproduce this behavior.

Thank you!

**Closed by composerinteralia** 2020-04-12 14:15 UTC
