### ISSUE TITLE
Unable to modify factories via a Rails Convention

### ISSUE THREAD

**Issue by BenMorganIO** [thoughtbot/factory_bot_rails#151] opened 2014-11-29 06:26 UTC
I'm trying to use `FactoryGirl.modify`, but it appears that when I place the `user_factory_decorator.rb` file in the factories folder, I'm greeted with a:

``` ruby
Factory not registered: user (ArgumentError)
```

Is there a way to be able to tell `FactoryGirl` to _not_ look at the factory decorators so that I may modify them?

**Comment by bxt** [comment] 2016-10-20 17:00
I think the problem is the loading order of factory files. If you do a `FactoryGirl.modify` in one file, without having the file with `FactoryGirl.define` loaded, you get this error.

I'm not sure if this is a bug or expected behavior. If you somehow saved the calls to `modify` for later, you wouldn't get an error if you modified any non-existing factories, which is equally undesirable. I got around it by putting all the decorators into their own directory which factory girl doesn't load at first and then loading them afterwards using:

    Dir[Rails.root.join("spec/factory_decorators/**/*.rb")].each { |f| require f }

in my `rails_helper.rb`. Maybe the default loading process of FactoryGirl should be adjusted to match this use-case.

**Comment by BenMorganIO** [comment] 2016-10-20 22:13
@bxt yep, that's what I've been doing as well :)

**Comment by composerinteralia** [comment] 2018-06-19 12:38
Thanks for the issue! It seems like you have find a reasonable workaround for your use case, so I am going to close this issue. 

factory_bot_rails looks for definitions in `factories`, `spec/factories`, and `test/factories`. I don't think we would want to make any additional assumptions about the directory structure. What may work for this use case may not work at all for other use cases.

**Closed by composerinteralia** 2018-06-19 12:38 UTC
