### ISSUE TITLE
factories generated in test instead of spec directory

### ISSUE THREAD

**Issue by Jakanapes** [thoughtbot/factory_bot_rails#263] opened 2018-03-08 15:38 UTC
recently switched from factory_girl 4.8.2 to factory_bot 4.8.2.

Factories generated are winding up in the test/factories directory instead of spec/factories.

factory_girl rails is in both the development and test groups in the gemfile

config is

```ruby
config.generators do |g|
      g.test_framework :rspec,
                       :fixture => true
      g.fixture_replacement :factory_bot
    end
```

I tried adding a specific

```ruby
      g.factory_bot dir: 'spec/factories'
```

Nothing seems to work

**Comment by unixc3t** [comment] 2018-03-30 03:38
@Jakanapes 
group :development, :test do

   gem "factory_bot_rails"
   gem "factory_bot"

end

config.generators do |g|
      g.test_framework :rspec, fixture: true
      g.fixture_replacement :factory_bot, dir: 'spec/factories'

    end

**Comment by odlp** [comment] 2018-06-01 16:44
@Jakanapes are you using `rspec` or `rspec-rails` in your Gemfile?

If you use `rspec-rails` it should configure the test framework for Rails:
https://github.com/rspec/rspec-rails/blob/01277163e4c164f59a7113229b159cdbd995b852/lib/rspec-rails.rb#L21

Which `factory_bot_rails` should reference & generate in the correct folder:
https://github.com/thoughtbot/factory_bot_rails/blob/a40e22c36fc4a95b12c8392a4bbc92a15a277a5d/lib/factory_bot_rails/generator.rb#L23-L24

**Comment by nnc** [comment] 2018-06-25 15:10
Also make sure `rspec-rails` comes before `factory_bot_rails` in your Gemfile.

```ruby
group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end
```

I had the same issue with factories being placed in `test/factories` directory, but turns out it was just because `rspec-rails` wasn't loaded yet, so test framework in Rails wasn't set to `:rspec` yet.

**Comment by composerinteralia** [comment] 2018-07-10 00:32
Thanks everyone. I wasn't able to reproduce this, and the order of the gems in my Gemfile didn't make any difference. Would you be able to link to a sample app that reproduces this?

**Comment by composerinteralia** [comment] 2018-07-18 03:09
I'm going to close this for now. Feel free to reopen if this is still a problem and you are able to provide some more information. Thanks!

**Closed by composerinteralia** 2018-07-18 03:09 UTC

**Comment by jimchild49** [comment] 2018-09-23 12:34
This still happens to me too, am not sure what produce the issue, but to add more context this happens when you already have the unit tests in your app and someday you decide to use rspec + factory bot. I retried by removing the default testing folder "test" altogether, and generating the factory will re-create the folder test and put the factories on it

**Comment by henrystewart** [comment] 2021-12-04 19:52
> Also make sure `rspec-rails` comes before `factory_bot_rails` in your Gemfile.
> 
> ```ruby
> group :development, :test do
>   gem 'rspec-rails'
>   gem 'factory_bot_rails'
> end
> ```
> 
> I had the same issue with factories being placed in `test/factories` directory, but turns out it was just because `rspec-rails` wasn't loaded yet, so test framework in Rails wasn't set to `:rspec` yet.

Fixed it for me. Thank you.
