### ISSUE TITLE
ActiveRecord reports build_stubbed to be persisted

### ISSUE THREAD

**Issue by rpbaptist** [thoughtbot/factory_bot_rails#266] opened 2018-04-06 11:37 UTC
Versioning:

factory_bot_rails: 4.8.2
rails: 5.1.5
ruby: 2.5.1
mysql2: 0.4.10

For example, when I want check if something is `#persisted?` or `#new_record?` it will report unexpected outcome:

```
Loading test environment (Rails 5.1.5)
[1] pry(main)> user = FactoryBot.build_stubbed :user
=> #<User id: 1001, email: "angelo_erdman@jaskolski.info">
[2] pry(main)> user.persisted?
=> true
[3] pry(main)> User.count
   (1.2ms)  SELECT COUNT(*) FROM `users`
=> 0
```

**Comment by composerinteralia** [comment] 2018-04-28 16:35
Thanks @rpbaptist. This is the intended behavior when using `build_stubbed`. It creates a record that looks like it is `persisted?` (i.e. is has an `id`), but will raise an error if you call methods that would hit the database (like `update` or `save`). At first glance I don't see great documentation on this in `factory_bot`, and you are not the first to have questions (see thoughtbot/factory_bot#1004 for example). So I think we should close this issue, but maybe open a documentation issue on `factory_bot`.

**Comment by composerinteralia** [comment] 2018-06-17 16:18
Closing for now. Thanks for your help!

**Closed by composerinteralia** 2018-06-17 16:18 UTC
