### ISSUE TITLE
FactoryGirl builds uninitialized object on first call, then works as expected

### ISSUE THREAD

**Issue by george** [thoughtbot/factory_bot_rails#125] opened 2014-01-24 12:41 UTC
(cross-posted from [StackOverflow](http://stackoverflow.com/questions/21176101))

Using:
- `factory_girl_rails v4.3.0` 
- `rails v4.0.1`
- `rspec-rails v2.14.0`

My first call to `FactoryGirl.build` returns an object all `nil` attributes.  If I call it again, it builds the object as expected, per the factory definition.  Here's a pry session to demonstrate the aberrant behavior:

```
∴ rspec ./spec/controllers/admin/base_controller_spec.rb:10
Run options: include {:locations=>{"./spec/controllers/admin/base_controller_spec.rb"=>[10]}}

Frame number: 0/25

From: /Users/george/work/salescrm/spec/support/controller_helpers.rb @ line 3 ControllerHelpers#sign_in:

     2:   def sign_in(user_type = nil)
 =>  3: binding.pry
     4:     user = FactoryGirl.create(user_type) unless user_type.nil?
     5:
     6:     if user.nil?
     7:       request.env['warden'].stub(:authenticate!).
     8:         and_throw(:warden, {:scope => :user})
     9:       controller.stub :current_user => nil
    10:     else
    11:       request.env['warden'].stub :authenticate! => user
    12:       controller.stub :current_user => user
    13:     end
    14:   end

[1] salescrm(#<RSpec::Core::ExampleGroup::Nested_1>) »  FactoryGirl::VERSION
=> "4.3.0"
[2] salescrm(#<RSpec::Core::ExampleGroup::Nested_1>) »  user_type
=> :admin_user
[3] salescrm(#<RSpec::Core::ExampleGroup::Nested_1>) »  FactoryGirl.build(user_type)
=> #<User:0x007fbc8e010d68> {
                      :id => nil,
                   :email => nil,
      :encrypted_password => "",
    :reset_password_token => nil,
  :reset_password_sent_at => nil,
     :remember_created_at => nil,
           :sign_in_count => 0,
      :current_sign_in_at => nil,
         :last_sign_in_at => nil,
      :current_sign_in_ip => nil,
         :last_sign_in_ip => nil,
              :created_at => nil,
              :updated_at => nil,
                :username => nil,
              :first_name => nil,
               :last_name => nil,
              :roles_mask => nil
}
[4] salescrm(#<RSpec::Core::ExampleGroup::Nested_1>) »  FactoryGirl.build(user_type)
=> #<User:0x007fbc8533ac90> {
                      :id => nil,
                   :email => "jan@email.com",
      :encrypted_password => "$2a$04$ROK0DlxigvTmgXY.kNsdL.z3R15cbZM60UbDi4iIqMtX.C1g6Fiii",
    :reset_password_token => nil,
  :reset_password_sent_at => nil,
     :remember_created_at => nil,
           :sign_in_count => 0,
      :current_sign_in_at => nil,
         :last_sign_in_at => nil,
      :current_sign_in_ip => nil,
         :last_sign_in_ip => nil,
              :created_at => nil,
              :updated_at => nil,
                :username => "jan_blogs",
              :first_name => "Jan",
               :last_name => "Blogs",
              :roles_mask => 1
}
```

And the factory:

```
FactoryGirl.define do
  factory :user do
    email 'joe@email.com'
    username 'joe_blogs'
    password 'my_password'
    first_name 'Joe'
    last_name 'Blogs'

    factory :admin_user do
      first_name 'Jan'
      email 'jan@email.com'
      username 'jan_blogs'
      password 'my_password'

      roles [:admin]
    end
  end
end
```

Any ideas what I'm doing wrong or what's going on?  Thanks.

**Comment by joshuaclayton** [comment] 2015-03-15 02:19
@george were you able to make any progress on this? Without access to the codebase, debugging something like this is fairly difficult. The factory itself looks fine, but assuming there's no strange setup or overriding of FG behavior, you shouldn't be running into this. Possibly an issue with spring?

**Comment by composerinteralia** [comment] 2018-06-19 12:28
I'm going to close this since we are unable to reproduce it and it hasn't come up again in a long time. Thanks!

**Closed by composerinteralia** 2018-06-19 12:28 UTC
