### ISSUE TITLE
4.9.0 Gem Not Published to Rubygems

### ISSUE THREAD

**Issue by nrowegt** [thoughtbot/factory_bot_rails#267] opened 2018-04-10 17:41 UTC
![image](https://user-images.githubusercontent.com/1641120/38573676-d27c8c3e-3cc4-11e8-9599-29963041379b.png)

**Comment by mikegee** [comment] 2018-04-11 16:58
This issue is a duplicate of https://github.com/thoughtbot/factory_bot_rails/issues/261, https://github.com/thoughtbot/factory_bot_rails/issues/260, https://github.com/thoughtbot/factory_bot_rails/issues/255, and https://github.com/thoughtbot/factory_bot_rails/issues/250.

**Closed** 2018-04-11 17:00 UTC
