### ISSUE TITLE
Memory leaks when I add `factory_girl_rails` in `development` env

### ISSUE THREAD

**Issue by Mik-die** [thoughtbot/factory_bot_rails#127] opened 2014-02-17 20:25 UTC
I add `factory_girl_rails` in `development` environment to automatically generate factories for my specs.

But each http request creates some instances of `FactoryGirl::Declaration::Implicit`, and they are not cleared by GC.
- ruby 2.0.0p247
- Rails 4.0.2
- Puma 2.7.1
- factory_girl (4.4.0) 
- factory_girl_rails (4.4.0) 

P.s. don't sure this issue is related to this gem, but, at one hand, generators in `factory_girl_rails` is not meaningful without using in dev env, and, at other hand, `factory_girl` without `factory_girl_rails` is not useful in dev env.

**Comment by composerinteralia** [comment] 2018-06-19 12:32
I'm going to close this issue since it is quite old and I'm not we have enough information to reproduce the problem. If you can still reproduce this on a current version of FactoryBot, please feel free to reopen the issue. I will definitely keep an eye out for this in the meantime. Thanks!

**Closed by composerinteralia** 2018-06-19 12:32 UTC
