### ISSUE TITLE
Issue with Rails 5.1 required belongs_to

### ISSUE THREAD

**Issue by PaddyDwyer** [thoughtbot/factory_bot_rails#232] opened 2017-04-12 13:13 UTC
After updating to rails 5.1 I have an issue with the way belongs to associations are created.

Prior to rails 5.1 I had the factory

    factory :user do
       address
    end

Address is a polymorphic association.
When I `create :user` I get a message saying addressable is required. That's coming from when the address is created and saved.

I'm getting around this for now by doing

    factory :user do
       after(:create) {|user| user.address = build :address}
    end

**Comment by baberthal** [comment] 2017-05-02 16:24
Experiencing this issue as well, though the error message is simply:
```
ActiveRecord::RecordInvalid:
  Validation failed: Taggings is invalid
```

Can confirm it only happens on a polymorphic relationship, seemingly (though not 100% sure) with 'virtual' attributes.

Using the block form of `create` bypasses the issue:

```ruby
model = create(:model) do |m|
  m.tags = 'hello, there'
end 
```

Relevant Backtrace:
```
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:15:in `create'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `tap'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
${HOME}/.rvm/gems/ruby-2.4.1@project/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
```

**Comment by joemsak** [comment] 2017-05-02 17:56
I'm finding I have to change a lot of my `before(:create)` hooks into `after(:create)`s because the `belongs_to` record must exist first -- tests are starting to pass for me since doing that -- will report if anything changes

**Comment by teohm** [comment] 2017-07-10 06:06
Has anyone identified the root cause?

**Comment by billguy** [comment] 2017-07-11 14:57
This is probably related to https://github.com/rails/rails/pull/18937

**Comment by subelsky** [comment] 2017-08-30 17:21
@PaddyDwyer's comment saved me, though in my case I have to do it in a `before(:create)` block

**Comment by composerinteralia** [comment] 2018-10-31 02:33
You are getting this error because factory_bot `create`s the associated address before assigning it to the user. This, as others have mentioned, fails because of the default belongs_to validations in Rails 5.

If you want to `build` the address instead you can use:

```rb
factory :user do
  association :user, strategy: :build 
end
```

Then the user and address will get saved together.

I'll open a separate issue on factory_bot improve support for polymorphic associations, at least through documentation, and maybe through changes to the library as well.

Thanks!

**Closed by composerinteralia** 2018-10-31 02:33 UTC
