### ISSUE TITLE
5.0.x does not play well with Spring

### ISSUE THREAD

**Issue by maestromac** [thoughtbot/factory_bot_rails#342] opened 2019-05-31 19:42 UTC
Running spring + rspec with latest version of `factory_bot_rails` will pass on the first run and fail on subsequent runs with error similar to below. 
```
Errno::ENOENT:
  No such file or directory @ rb_file_s_size - /var/folders/d9/xwbrcf1505s4kwdgyvt51j_00000gn/T/image120190531-3757-wty3vi.jpeg

```
Example in the image below
![](https://cl.ly/0accd453ec58/Image%202019-05-31%20at%203.33.11%20PM.png)
- This wasn't a problem with 4.11
- This only occurs with system and request specs
- The error is reproducible on both 5.0.1 and 5.0.2

It was not apparent that upgrading was the case until I run `git bisect` on the codebase. Could be something related the profile pic on our [user's factory ](https://github.com/thepracticaldev/dev.to/blob/master/spec/factories/users.rb#L16).  Happy to provide additional info.
```
gem "rspec-rails", "~> 3.8" 
gem "spring", "~> 2.0" 
gem "rails", "~> 5.2.3"
```

**Comment by composerinteralia** [comment] 2019-06-07 17:44
Thanks for the issue. I was able to reproduce this. It has to do with the fact that you are creating a `Rack::Test::UploadedFile.new` in the `FactoryBot.define` block. There seems to be a reference to a tempfile that no longer exists. I will look into this further, but in the meantime it looks like you can work around the issue by creating the `Rack::Test::UploadedFile` in the attribute block:

```rb
image_file = Rails.root.join("spec", "support", "fixtures", "images", "image1.jpeg")

factory :user do
  profile_image { Rack::Test::UploadedFile.new(image_file, "image/jpeg") }
end
```

**Comment by maestromac** [comment] 2019-06-07 17:58
Thanks! I'll go ahead and do that for now.

**Comment by composerinteralia** [comment] 2019-09-20 21:30
Some more details here:

1. On the first test run, spring starts up and the application initializes
2. factory_bot loads and this factory definition instantiates a `Rack::Test::UploadedFile`
3. [`Rack::Test::UploadedFile`](https://github.com/rack-test/rack-test/blob/a2f762d5abc2ead277dab51794d22083b72809ea/lib/rack/test/uploaded_file.rb#L23) creates a tempfile, and and `ObjectSpace` finalizer to clean up the temp file
4. The test runs successfully
5. The finalizer runs and cleans up the temp file. This is surprising to me, since factory_bot is still holding a reference to the object.
6. On the second test run, the application is preloaded. (If any files have changed spring will reload the application and we won't see the error)
7. factory_bot is already loaded, and holds a reference to the `Rack::Test::UploadedFile`, but its tempfile has already been cleaned up
8. Tests fail as described in this PR

We could solve this by adding back the logic to reload factory_bot after every spring fork, but I don't love the idea of adding references to spring back into factory_bot (we removed that in https://github.com/thoughtbot/factory_bot_rails/commit/02a0f584876ff5c7a6d6fa4965da58ed70464a73).

I think the first step is to dig a little more into why that rack finalizer is running when it does.

**Comment by composerinteralia** [comment] 2019-09-21 18:43
Aha, this has to do with the fact that [spring runs in a forked process](https://github.com/rails/spring/blob/22df9100c81c21777f792facc2d4c72cd4aa1fef/lib/spring/application.rb#L175). Consider this:

```rb
ObjectSpace.define_finalizer({}, proc { puts "Finalized" }) 

fork
```

Running this code you will see "Finalized" printed twice, once for the original process and once for the forked process.

So the tempfile gets deleted by the finalizer in the spring forked process, but we still hold a reference to the `Rack::Test::UploadedFile` in the main process, and in any later spring forks.

**Comment by composerinteralia** [comment] 2019-10-25 17:48
I am going to close this issue without fixing for now. There is a reasonable workaround, and we also have https://github.com/thoughtbot/factory_bot/issues to improve the file upload experience in factory_bot.

More generally, factory_bot does not currently have great support for using non-factory_bot code to help in building object instances. We are tracking this in https://github.com/thoughtbot/factory_bot/issues/1252.

**Closed by composerinteralia** 2019-10-25 17:48 UTC
